### ISSUE TITLE
需要外放自主管理贴纸

### ISSUE THREAD

**Issue by ESC-LIC** [ksvcmc/KMCFuFilter_Android#7]
1.获得的贴纸无法本地化管理
2.DEMO中的手势贴纸没有实现（AR动作）
3.人脸识别检测接口没有外放--体验不够好，如果单方面可以视是否被识别到脸部比较好

**Comment by sujia** [comment]
@ESC-LIC [v1.0.9](https://github.com/ksvcmc/KMCFuFilter_Android/releases/tag/v1.0.9)本已上线，
支持从本地加载贴纸，也增加了几款动作贴纸，使用方法可以参考[wiki](https://github.com/ksvcmc/KMCFuFilter_Android/wiki)以及demo
